name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou master, selon le nom de votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Copy public to docs
      run: |
        mkdir -p docs
        cp -R public/* docs/
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m "Copy public to docs for GitHub Pages" -a || echo "No changes to commit"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
